version: "2"

networks:
  backend:
    driver: bridge
  frontend:
    external: true
services:
  rmq:
    hostname: rmq
    container_name: rmq
    image: "rabbitmq:3.9-management"
    ports:
      - 15672:15672
    networks:
      - backend
    volumes:
      - "./rmq-data:/var/lib/rabbitmq"
  psql:
    container_name: psql
    build:
      context: ./psql
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      - POSTGRES_USER=notif_user
      - POSTGRES_PASSWORD=notif_pass
      - POSTGRES_DB=notification-db
    volumes:
      - "./psql-data:/bitnami/postgresql"
  notification-api:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.rabbitmq.host=rmq
      - spring.datasource.url=jdbc:postgresql://psql:5432/notification-db
    depends_on:
      - psql
      - rmq
    networks:
      - backend
      - frontend
    ports:
      - 8080:8080
    restart: on-failure